def generate_ea(p):
    name = p["name"]
    author = p["author"]
    version = p["version"]
    copyright_ = p["copyright"]
    lot = p["lot"]
    use_mm = p["use_mm"]
    risk = p["risk"]
    sl = p["sl"]
    tp = p["tp"]
    trail = p["trail"]
    strategy = p["strategy"]
    fast_ma = p["fast_ma"]
    slow_ma = p["slow_ma"]
    rsi_period = p["rsi_period"]
    rsi_os = p["rsi_os"]
    rsi_ob = p["rsi_ob"]
    filter_trend = p["filter_trend"]
    filter_session = p["filter_session"]
    filter_spread = p["filter_spread"]
    max_spread = p["max_spread"]
    breakeven = p["breakeven"]
    partial_close = p["partial_close"]
    use_magic = p["use_magic"]
    magic_num = p["magic_num"]

    lines = []

    lines.append(f"//+------------------------------------------------------------------+")
    lines.append(f"//|  {name}.mq5                                                      |")
    lines.append(f"//|  Copyright {copyright_}, {author}                                |")
    lines.append(f"//|  Generated by MT5 Code Generator                                 |")
    lines.append(f"//+------------------------------------------------------------------+")
    lines.append(f"#property copyright \"Copyright {copyright_}, {author}\"")
    lines.append(f"#property version   \"{version}\"")
    lines.append(f"#property strict")
    lines.append("")
    lines.append("#include <Trade\\Trade.mqh>")
    lines.append("#include <Trade\\PositionInfo.mqh>")
    lines.append("")

    lines.append("//--- Input Parameters")
    if use_mm:
        lines.append(f"input double   InpRisk        = {risk};         // Rischio % per trade")
    else:
        lines.append(f"input double   InpLotSize     = {lot};         // Lotto fisso")
    lines.append(f"input int      InpStopLoss    = {sl};          // Stop Loss (pips)")
    lines.append(f"input int      InpTakeProfit  = {tp};         // Take Profit (pips)")
    if int(trail) > 0:
        lines.append(f"input int      InpTrailStop   = {trail};          // Trailing Stop (pips)")

    if "MA" in strategy or "Doppia" in strategy:
        lines.append(f"input int      InpFastMA      = {fast_ma};           // Periodo MA veloce")
        lines.append(f"input int      InpSlowMA      = {slow_ma};          // Periodo MA lenta")
    if "RSI" in strategy or "Doppia" in strategy:
        lines.append(f"input int      InpRSIPeriod   = {rsi_period};          // Periodo RSI")
        lines.append(f"input double   InpRSIOversold = {rsi_os};          // RSI Oversold")
        lines.append(f"input double   InpRSIOverbought = {rsi_ob};        // RSI Overbought")
    if "MACD" in strategy:
        lines.append(f"input int      InpMACDFast    = 12;           // MACD Fast EMA")
        lines.append(f"input int      InpMACDSlow    = 26;           // MACD Slow EMA")
        lines.append(f"input int      InpMACDSignal  = 9;            // MACD Signal")
    if "Bollinger" in strategy:
        lines.append(f"input int      InpBBPeriod    = 20;           // Bande Bollinger periodo")
        lines.append(f"input double   InpBBDev       = 2.0;          // Bande Bollinger deviazione")
    if "Stochastic" in strategy:
        lines.append(f"input int      InpStochK      = 5;            // Stocastico %K")
        lines.append(f"input int      InpStochD      = 3;            // Stocastico %D")
        lines.append(f"input int      InpStochSlow   = 3;            // Stocastico Slow")
    if "Breakout" in strategy:
        lines.append(f"input int      InpBreakoutBars = 20;          // N candele per breakout")
    if filter_trend:
        lines.append(f"input int      InpTrendMA     = 200;          // MA trend filter")
    if filter_spread:
        lines.append(f"input int      InpMaxSpread   = {max_spread};          // Spread massimo (punti)")
    if use_magic:
        lines.append(f"input int      InpMagicNumber = {magic_num};       // Magic Number")
    if breakeven:
        lines.append(f"input int      InpBreakEven   = 30;           // Break Even (pips)")
    lines.append("")

    lines.append("//--- Global variables")
    lines.append("CTrade         trade;")
    lines.append("CPositionInfo  posInfo;")
    lines.append("int            handle_fast = INVALID_HANDLE;")
    lines.append("int            handle_slow = INVALID_HANDLE;")
    if "RSI" in strategy or "Doppia" in strategy:
        lines.append("int            handle_rsi  = INVALID_HANDLE;")
    if "MACD" in strategy:
        lines.append("int            handle_macd = INVALID_HANDLE;")
    if "Bollinger" in strategy:
        lines.append("int            handle_bb   = INVALID_HANDLE;")
    if "Stochastic" in strategy:
        lines.append("int            handle_stoch = INVALID_HANDLE;")
    if filter_trend:
        lines.append("int            handle_trend = INVALID_HANDLE;")
    lines.append("datetime       lastBarTime  = 0;")
    lines.append("")

    lines.append("//+------------------------------------------------------------------+")
    lines.append("//| Expert initialization function                                    |")
    lines.append("//+------------------------------------------------------------------+")
    lines.append("int OnInit()")
    lines.append("{")
    if use_magic:
        lines.append(f"   trade.SetExpertMagicNumber(InpMagicNumber);")
    lines.append(f"   trade.SetDeviationInPoints(10);")
    lines.append("")

    if "MA" in strategy or "Doppia" in strategy:
        lines.append(f"   handle_fast = iMA(_Symbol, PERIOD_CURRENT, InpFastMA, 0, MODE_EMA, PRICE_CLOSE);")
        lines.append(f"   handle_slow = iMA(_Symbol, PERIOD_CURRENT, InpSlowMA, 0, MODE_EMA, PRICE_CLOSE);")
        lines.append(f"   if(handle_fast == INVALID_HANDLE || handle_slow == INVALID_HANDLE)")
        lines.append(f"   {{")
        lines.append(f"      Print(\"Errore creazione handle MA\");")
        lines.append(f"      return(INIT_FAILED);")
        lines.append(f"   }}")
    if "RSI" in strategy or "Doppia" in strategy:
        lines.append(f"   handle_rsi = iRSI(_Symbol, PERIOD_CURRENT, InpRSIPeriod, PRICE_CLOSE);")
        lines.append(f"   if(handle_rsi == INVALID_HANDLE)")
        lines.append(f"   {{")
        lines.append(f"      Print(\"Errore creazione handle RSI\");")
        lines.append(f"      return(INIT_FAILED);")
        lines.append(f"   }}")
    if "MACD" in strategy:
        lines.append(f"   handle_macd = iMACD(_Symbol, PERIOD_CURRENT, InpMACDFast, InpMACDSlow, InpMACDSignal, PRICE_CLOSE);")
    if "Bollinger" in strategy:
        lines.append(f"   handle_bb = iBands(_Symbol, PERIOD_CURRENT, InpBBPeriod, 0, InpBBDev, PRICE_CLOSE);")
    if "Stochastic" in strategy:
        lines.append(f"   handle_stoch = iStochastic(_Symbol, PERIOD_CURRENT, InpStochK, InpStochD, InpStochSlow, MODE_SMA, STO_LOWHIGH);")
    if filter_trend:
        lines.append(f"   handle_trend = iMA(_Symbol, PERIOD_CURRENT, InpTrendMA, 0, MODE_SMA, PRICE_CLOSE);")
    lines.append("")
    lines.append("   return(INIT_SUCCEEDED);")
    lines.append("}")
    lines.append("")

    lines.append("//+------------------------------------------------------------------+")
    lines.append("//| Expert deinitialization function                                  |")
    lines.append("//+------------------------------------------------------------------+")
    lines.append("void OnDeinit(const int reason)")
    lines.append("{")
    lines.append("   if(handle_fast != INVALID_HANDLE) IndicatorRelease(handle_fast);")
    lines.append("   if(handle_slow != INVALID_HANDLE) IndicatorRelease(handle_slow);")
    if "RSI" in strategy or "Doppia" in strategy:
        lines.append("   if(handle_rsi  != INVALID_HANDLE) IndicatorRelease(handle_rsi);")
    if "MACD" in strategy:
        lines.append("   if(handle_macd != INVALID_HANDLE) IndicatorRelease(handle_macd);")
    if "Bollinger" in strategy:
        lines.append("   if(handle_bb   != INVALID_HANDLE) IndicatorRelease(handle_bb);")
    if filter_trend:
        lines.append("   if(handle_trend != INVALID_HANDLE) IndicatorRelease(handle_trend);")
    lines.append("}")
    lines.append("")

    lines.append("//+------------------------------------------------------------------+")
    lines.append("//| Expert tick function                                              |")
    lines.append("//+------------------------------------------------------------------+")
    lines.append("void OnTick()")
    lines.append("{")
    lines.append("   //--- Esegui solo su nuova candela")
    lines.append("   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);")
    lines.append("   if(currentBarTime == lastBarTime) return;")
    lines.append("   lastBarTime = currentBarTime;")
    lines.append("")

    if filter_spread:
        lines.append("   //--- Filtro spread")
        lines.append("   long spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);")
        lines.append("   if(spread > InpMaxSpread) return;")
        lines.append("")

    if filter_session:
        lines.append("   //--- Filtro sessione (Londra 07:00-16:00 UTC)")
        lines.append("   MqlDateTime dt;")
        lines.append("   TimeToStruct(TimeCurrent(), dt);")
        lines.append("   if(dt.hour < 7 || dt.hour >= 16) return;")
        lines.append("")

    if breakeven:
        lines.append("   //--- Gestione Break Even")
        lines.append("   ManageBreakEven();")
        lines.append("")

    if int(trail) > 0:
        lines.append("   //--- Gestione Trailing Stop")
        lines.append("   ManageTrailingStop();")
        lines.append("")

    lines.append("   //--- Leggi segnali")
    lines.append("   int signal = GetSignal();")
    lines.append("   if(signal == 0) return;")
    lines.append("")
    lines.append("   //--- Calcola lotto")
    lines.append("   double lots = CalculateLotSize();")
    lines.append("   if(lots <= 0) return;")
    lines.append("")
    lines.append("   //--- Apri posizione")
    lines.append("   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);")
    lines.append("   int digits   = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);")
    lines.append("   double pipValue = (digits == 5 || digits == 3) ? point * 10 : point;")
    lines.append("")
    lines.append("   if(signal == 1 && CountPositions(POSITION_TYPE_BUY) == 0)")
    lines.append("   {")
    lines.append("      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);")
    lines.append("      double sl  = (InpStopLoss  > 0) ? ask - InpStopLoss  * pipValue : 0;")
    lines.append("      double tp  = (InpTakeProfit > 0) ? ask + InpTakeProfit * pipValue : 0;")
    lines.append("      trade.Buy(lots, _Symbol, ask, sl, tp, \"" + name + "\");")
    lines.append("   }")
    lines.append("   else if(signal == -1 && CountPositions(POSITION_TYPE_SELL) == 0)")
    lines.append("   {")
    lines.append("      double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);")
    lines.append("      double sl  = (InpStopLoss  > 0) ? bid + InpStopLoss  * pipValue : 0;")
    lines.append("      double tp  = (InpTakeProfit > 0) ? bid - InpTakeProfit * pipValue : 0;")
    lines.append("      trade.Sell(lots, _Symbol, bid, sl, tp, \"" + name + "\");")
    lines.append("   }")
    lines.append("}")
    lines.append("")

    lines.append("//+------------------------------------------------------------------+")
    lines.append("//| Funzione segnale                                                  |")
    lines.append("//+------------------------------------------------------------------+")
    lines.append("int GetSignal()")
    lines.append("{")

    if "MA Crossover" in strategy or "Doppia" in strategy:
        lines.append("   double fast[], slow[];")
        lines.append("   ArraySetAsSeries(fast, true);")
        lines.append("   ArraySetAsSeries(slow, true);")
        lines.append("   if(CopyBuffer(handle_fast, 0, 0, 3, fast) < 3) return 0;")
        lines.append("   if(CopyBuffer(handle_slow, 0, 0, 3, slow) < 3) return 0;")
        lines.append("")
        if "Doppia" in strategy:
            lines.append("   double rsi[];")
            lines.append("   ArraySetAsSeries(rsi, true);")
            lines.append("   if(CopyBuffer(handle_rsi, 0, 0, 3, rsi) < 3) return 0;")
            lines.append("")
            lines.append("   bool buySignal  = fast[1] > slow[1] && fast[2] <= slow[2] && rsi[1] < InpRSIOverbought;")
            lines.append("   bool sellSignal = fast[1] < slow[1] && fast[2] >= slow[2] && rsi[1] > InpRSIOversold;")
        else:
            lines.append("   bool buySignal  = fast[1] > slow[1] && fast[2] <= slow[2];")
            lines.append("   bool sellSignal = fast[1] < slow[1] && fast[2] >= slow[2];")
    elif "RSI" in strategy:
        lines.append("   double rsi[];")
        lines.append("   ArraySetAsSeries(rsi, true);")
        lines.append("   if(CopyBuffer(handle_rsi, 0, 0, 3, rsi) < 3) return 0;")
        lines.append("")
        lines.append("   bool buySignal  = rsi[2] < InpRSIOversold  && rsi[1] >= InpRSIOversold;")
        lines.append("   bool sellSignal = rsi[2] > InpRSIOverbought && rsi[1] <= InpRSIOverbought;")
    elif "MACD" in strategy:
        lines.append("   double macd[], signal_buf[];")
        lines.append("   ArraySetAsSeries(macd, true);")
        lines.append("   ArraySetAsSeries(signal_buf, true);")
        lines.append("   if(CopyBuffer(handle_macd, MAIN_LINE,   0, 3, macd)       < 3) return 0;")
        lines.append("   if(CopyBuffer(handle_macd, SIGNAL_LINE, 0, 3, signal_buf) < 3) return 0;")
        lines.append("")
        lines.append("   bool buySignal  = macd[1] > signal_buf[1] && macd[2] <= signal_buf[2];")
        lines.append("   bool sellSignal = macd[1] < signal_buf[1] && macd[2] >= signal_buf[2];")
    elif "Bollinger" in strategy:
        lines.append("   double bb_upper[], bb_lower[], close[];")
        lines.append("   ArraySetAsSeries(bb_upper, true);")
        lines.append("   ArraySetAsSeries(bb_lower, true);")
        lines.append("   ArraySetAsSeries(close, true);")
        lines.append("   if(CopyBuffer(handle_bb, UPPER_BAND, 0, 3, bb_upper) < 3) return 0;")
        lines.append("   if(CopyBuffer(handle_bb, LOWER_BAND, 0, 3, bb_lower) < 3) return 0;")
        lines.append("   if(CopyClose(_Symbol, PERIOD_CURRENT, 0, 3, close)   < 3) return 0;")
        lines.append("")
        lines.append("   bool buySignal  = close[2] < bb_lower[2] && close[1] >= bb_lower[1];")
        lines.append("   bool sellSignal = close[2] > bb_upper[2] && close[1] <= bb_upper[1];")
    elif "Stochastic" in strategy:
        lines.append("   double stoch_k[], stoch_d[];")
        lines.append("   ArraySetAsSeries(stoch_k, true);")
        lines.append("   ArraySetAsSeries(stoch_d, true);")
        lines.append("   if(CopyBuffer(handle_stoch, MAIN_LINE,   0, 3, stoch_k) < 3) return 0;")
        lines.append("   if(CopyBuffer(handle_stoch, SIGNAL_LINE, 0, 3, stoch_d) < 3) return 0;")
        lines.append("")
        lines.append("   bool buySignal  = stoch_k[1] > stoch_d[1] && stoch_k[2] <= stoch_d[2] && stoch_k[1] < 80;")
        lines.append("   bool sellSignal = stoch_k[1] < stoch_d[1] && stoch_k[2] >= stoch_d[2] && stoch_k[1] > 20;")
    elif "Engulfing" in strategy:
        lines.append("   double open[], high[], low[], close[];")
        lines.append("   ArraySetAsSeries(open,  true);")
        lines.append("   ArraySetAsSeries(high,  true);")
        lines.append("   ArraySetAsSeries(low,   true);")
        lines.append("   ArraySetAsSeries(close, true);")
        lines.append("   if(CopyOpen (_Symbol, PERIOD_CURRENT, 0, 3, open)  < 3) return 0;")
        lines.append("   if(CopyHigh (_Symbol, PERIOD_CURRENT, 0, 3, high)  < 3) return 0;")
        lines.append("   if(CopyLow  (_Symbol, PERIOD_CURRENT, 0, 3, low)   < 3) return 0;")
        lines.append("   if(CopyClose(_Symbol, PERIOD_CURRENT, 0, 3, close) < 3) return 0;")
        lines.append("")
        lines.append("   bool bullEngulf = close[2] < open[2] && close[1] > open[1]")
        lines.append("                  && open[1]  < close[2] && close[1] > open[2];")
        lines.append("   bool bearEngulf = close[2] > open[2] && close[1] < open[1]")
        lines.append("                  && open[1]  > close[2] && close[1] < open[2];")
        lines.append("   bool buySignal  = bullEngulf;")
        lines.append("   bool sellSignal = bearEngulf;")
    elif "Breakout" in strategy:
        lines.append("   double high[], low[], close[];")
        lines.append("   ArraySetAsSeries(high,  true);")
        lines.append("   ArraySetAsSeries(low,   true);")
        lines.append("   ArraySetAsSeries(close, true);")
        lines.append("   if(CopyHigh (_Symbol, PERIOD_CURRENT, 1, InpBreakoutBars, high)  < InpBreakoutBars) return 0;")
        lines.append("   if(CopyLow  (_Symbol, PERIOD_CURRENT, 1, InpBreakoutBars, low)   < InpBreakoutBars) return 0;")
        lines.append("   if(CopyClose(_Symbol, PERIOD_CURRENT, 0, 2, close) < 2) return 0;")
        lines.append("")
        lines.append("   double highest = high[ArrayMaximum(high)];")
        lines.append("   double lowest  = low[ArrayMinimum(low)];")
        lines.append("   bool buySignal  = close[1] > highest;")
        lines.append("   bool sellSignal = close[1] < lowest;")
    else:
        lines.append("   bool buySignal  = false;")
        lines.append("   bool sellSignal = false;")

    if filter_trend:
        lines.append("")
        lines.append("   //--- Filtro trend MA200")
        lines.append("   double trend[];")
        lines.append("   ArraySetAsSeries(trend, true);")
        lines.append("   if(CopyBuffer(handle_trend, 0, 0, 2, trend) < 2) return 0;")
        lines.append("   double price = iClose(_Symbol, PERIOD_CURRENT, 1);")
        lines.append("   if(buySignal  && price < trend[1]) buySignal  = false;")
        lines.append("   if(sellSignal && price > trend[1]) sellSignal = false;")

    lines.append("")
    lines.append("   if(buySignal)  return  1;")
    lines.append("   if(sellSignal) return -1;")
    lines.append("   return 0;")
    lines.append("}")
    lines.append("")

    lines.append("//+------------------------------------------------------------------+")
    lines.append("//| Calcola dimensione lotto                                          |")
    lines.append("//+------------------------------------------------------------------+")
    lines.append("double CalculateLotSize()")
    lines.append("{")
    if use_mm:
        lines.append("   double balance  = AccountInfoDouble(ACCOUNT_BALANCE);")
        lines.append("   double riskAmt  = balance * InpRisk / 100.0;")
        lines.append("   double point    = SymbolInfoDouble(_Symbol, SYMBOL_POINT);")
        lines.append("   int    digits   = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);")
        lines.append("   double pipVal   = (digits == 5 || digits == 3) ? point * 10 : point;")
        lines.append("   double tickVal  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);")
        lines.append("   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);")
        lines.append("   double pipMoney = (tickVal / tickSize) * pipVal;")
        lines.append("   double lots     = (pipMoney > 0) ? riskAmt / (InpStopLoss * pipMoney) : 0.01;")
        lines.append("   double minLot   = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);")
        lines.append("   double maxLot   = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);")
        lines.append("   double stepLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);")
        lines.append("   lots = MathFloor(lots / stepLot) * stepLot;")
        lines.append("   lots = MathMax(minLot, MathMin(maxLot, lots));")
        lines.append("   return lots;")
    else:
        lines.append(f"   return InpLotSize;")
    lines.append("}")
    lines.append("")

    lines.append("//+------------------------------------------------------------------+")
    lines.append("//| Conta posizioni aperte per tipo                                   |")
    lines.append("//+------------------------------------------------------------------+")
    lines.append("int CountPositions(ENUM_POSITION_TYPE posType)")
    lines.append("{")
    lines.append("   int count = 0;")
    lines.append("   for(int i = PositionsTotal() - 1; i >= 0; i--)")
    lines.append("   {")
    lines.append("      if(posInfo.SelectByIndex(i))")
    lines.append("         if(posInfo.Symbol() == _Symbol &&")
    if use_magic:
        lines.append("            posInfo.Magic()  == InpMagicNumber &&")
    lines.append("            posInfo.PositionType() == posType)")
    lines.append("            count++;")
    lines.append("   }")
    lines.append("   return count;")
    lines.append("}")
    lines.append("")

    if breakeven:
        lines.append("//+------------------------------------------------------------------+")
        lines.append("//| Gestione Break Even                                               |")
        lines.append("//+------------------------------------------------------------------+")
        lines.append("void ManageBreakEven()")
        lines.append("{")
        lines.append("   double point   = SymbolInfoDouble(_Symbol, SYMBOL_POINT);")
        lines.append("   int    digits  = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);")
        lines.append("   double pipVal  = (digits == 5 || digits == 3) ? point * 10 : point;")
        lines.append("   for(int i = PositionsTotal() - 1; i >= 0; i--)")
        lines.append("   {")
        lines.append("      if(!posInfo.SelectByIndex(i)) continue;")
        lines.append("      if(posInfo.Symbol() != _Symbol) continue;")
        if use_magic:
            lines.append("      if(posInfo.Magic() != InpMagicNumber) continue;")
        lines.append("      double openPrice = posInfo.PriceOpen();")
        lines.append("      double currentSL = posInfo.StopLoss();")
        lines.append("      if(posInfo.PositionType() == POSITION_TYPE_BUY)")
        lines.append("      {")
        lines.append("         double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);")
        lines.append("         if(bid >= openPrice + InpBreakEven * pipVal && (currentSL < openPrice || currentSL == 0))")
        lines.append("            trade.PositionModify(posInfo.Ticket(), openPrice, posInfo.TakeProfit());")
        lines.append("      }")
        lines.append("      else if(posInfo.PositionType() == POSITION_TYPE_SELL)")
        lines.append("      {")
        lines.append("         double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);")
        lines.append("         if(ask <= openPrice - InpBreakEven * pipVal && (currentSL > openPrice || currentSL == 0))")
        lines.append("            trade.PositionModify(posInfo.Ticket(), openPrice, posInfo.TakeProfit());")
        lines.append("      }")
        lines.append("   }")
        lines.append("}")
        lines.append("")

    if int(trail) > 0:
        lines.append("//+------------------------------------------------------------------+")
        lines.append("//| Gestione Trailing Stop                                            |")
        lines.append("//+------------------------------------------------------------------+")
        lines.append("void ManageTrailingStop()")
        lines.append("{")
        lines.append("   double point   = SymbolInfoDouble(_Symbol, SYMBOL_POINT);")
        lines.append("   int    digits  = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);")
        lines.append("   double pipVal  = (digits == 5 || digits == 3) ? point * 10 : point;")
        lines.append("   double trail   = InpTrailStop * pipVal;")
        lines.append("   for(int i = PositionsTotal() - 1; i >= 0; i--)")
        lines.append("   {")
        lines.append("      if(!posInfo.SelectByIndex(i)) continue;")
        lines.append("      if(posInfo.Symbol() != _Symbol) continue;")
        if use_magic:
            lines.append("      if(posInfo.Magic() != InpMagicNumber) continue;")
        lines.append("      if(posInfo.PositionType() == POSITION_TYPE_BUY)")
        lines.append("      {")
        lines.append("         double bid    = SymbolInfoDouble(_Symbol, SYMBOL_BID);")
        lines.append("         double newSL  = bid - trail;")
        lines.append("         if(newSL > posInfo.StopLoss())")
        lines.append("            trade.PositionModify(posInfo.Ticket(), newSL, posInfo.TakeProfit());")
        lines.append("      }")
        lines.append("      else if(posInfo.PositionType() == POSITION_TYPE_SELL)")
        lines.append("      {")
        lines.append("         double ask   = SymbolInfoDouble(_Symbol, SYMBOL_ASK);")
        lines.append("         double newSL = ask + trail;")
        lines.append("         if(newSL < posInfo.StopLoss() || posInfo.StopLoss() == 0)")
        lines.append("            trade.PositionModify(posInfo.Ticket(), newSL, posInfo.TakeProfit());")
        lines.append("      }")
        lines.append("   }")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)
