def generate_indicator(p):
    name = p["name"]
    author = p["author"]
    version = p["version"]
    ind_type = p["type"]
    window = p["window"]
    period = p["period"]
    signal = p["signal"]
    ma_method = p["ma_method"]
    applied = p["applied"]
    arrows = p["arrows"]
    levels = p["levels"]
    level_high = p["level_high"]
    level_low = p["level_low"]
    alert = p["alert"]
    email = p["email"]
    push = p["push"]

    in_main = "Finestra principale" in window

    lines = []
    lines.append(f"//+------------------------------------------------------------------+")
    lines.append(f"//|  {name}.mq5                                                      |")
    lines.append(f"//|  Copyright 2025, {author}                                        |")
    lines.append(f"//|  Generated by MT5 Code Generator                                 |")
    lines.append(f"//+------------------------------------------------------------------+")
    lines.append(f"#property copyright \"Copyright 2025, {author}\"")
    lines.append(f"#property version   \"{version}\"")
    lines.append(f"#property indicator_{'chart' if in_main else 'separate'}")
    lines.append(f"#property strict")
    lines.append("")

    num_buffers = 1
    if arrows:
        num_buffers += 2
    if "MACD" in ind_type:
        num_buffers = 2
    if "Doppia" in ind_type:
        num_buffers = 2

    lines.append(f"#property indicator_buffers {num_buffers}")
    lines.append(f"#property indicator_plots   {num_buffers}")
    lines.append("")

    lines.append("//--- Plot 1: linea principale")
    if in_main:
        lines.append("#property indicator_type1   DRAW_LINE")
        lines.append("#property indicator_color1  clrDodgerBlue")
        lines.append("#property indicator_style1  STYLE_SOLID")
        lines.append("#property indicator_width1  2")
    else:
        lines.append("#property indicator_type1   DRAW_LINE")
        lines.append("#property indicator_color1  clrDodgerBlue")
        lines.append("#property indicator_width1  2")

    if "MACD" in ind_type or "Doppia" in ind_type:
        lines.append("")
        lines.append("//--- Plot 2: linea segnale")
        lines.append("#property indicator_type2   DRAW_LINE")
        lines.append("#property indicator_color2  clrOrangeRed")
        lines.append("#property indicator_width2  1")

    if arrows:
        lines.append("")
        idx = num_buffers - 1
        lines.append(f"//--- Frecce BUY/SELL")
        lines.append(f"#property indicator_type{idx}   DRAW_ARROW")
        lines.append(f"#property indicator_color{idx}  clrLime")
        lines.append(f"#property indicator_type{idx+1}  DRAW_ARROW")
        lines.append(f"#property indicator_color{idx+1} clrRed")

    if levels:
        lines.append("")
        lines.append(f"#property indicator_level1  {level_high}")
        lines.append(f"#property indicator_level2  {level_low}")
        lines.append(f"#property indicator_levelcolor clrGray")
        lines.append(f"#property indicator_levelstyle STYLE_DOT")

    lines.append("")
    lines.append("//--- Input Parameters")
    lines.append(f"input int    InpPeriod   = {period};        // Periodo principale")
    if "MACD" in ind_type:
        lines.append(f"input int    InpFast     = 12;             // EMA veloce")
        lines.append(f"input int    InpSlow     = 26;             // EMA lenta")
        lines.append(f"input int    InpSignal   = {signal};        // Periodo segnale")
    if "Bollinger" in ind_type:
        lines.append(f"input double InpDeviation = 2.0;           // Deviazione standard")
    if "Stochastic" in ind_type:
        lines.append(f"input int    InpSlowing  = 3;              // Rallentamento")
    lines.append(f"input ENUM_MA_METHOD    InpMAMethod  = {ma_method};  // Metodo MA")
    lines.append(f"input ENUM_APPLIED_PRICE InpApplied  = {applied};    // Applicato a")
    if alert or email or push:
        lines.append(f"input bool   InpAlerts   = true;           // Abilita notifiche")
    lines.append("")

    lines.append("//--- Buffer arrays")
    lines.append("double MainBuffer[];")
    if "MACD" in ind_type or "Doppia" in ind_type:
        lines.append("double SignalBuffer[];")
    if arrows:
        lines.append("double ArrowBuy[];")
        lines.append("double ArrowSell[];")
    lines.append("bool   alerted = false;")
    lines.append("")

    lines.append("//+------------------------------------------------------------------+")
    lines.append("//| Indicator initialization                                          |")
    lines.append("//+------------------------------------------------------------------+")
    lines.append("int OnInit()")
    lines.append("{")
    lines.append("   SetIndexBuffer(0, MainBuffer, INDICATOR_DATA);")
    lines.append("   PlotIndexSetString(0, PLOT_LABEL, \"" + name + "\");")
    if "MACD" in ind_type or "Doppia" in ind_type:
        lines.append("   SetIndexBuffer(1, SignalBuffer, INDICATOR_DATA);")
        lines.append("   PlotIndexSetString(1, PLOT_LABEL, \"Signal\");")
    if arrows:
        lines.append("   SetIndexBuffer(2, ArrowBuy,  INDICATOR_DATA);")
        lines.append("   SetIndexBuffer(3, ArrowSell, INDICATOR_DATA);")
        lines.append("   PlotIndexSetInteger(2, PLOT_ARROW, 233);")
        lines.append("   PlotIndexSetInteger(3, PLOT_ARROW, 234);")
        lines.append("   PlotIndexSetDouble(2,  PLOT_EMPTY_VALUE, EMPTY_VALUE);")
        lines.append("   PlotIndexSetDouble(3,  PLOT_EMPTY_VALUE, EMPTY_VALUE);")
    lines.append(f"   IndicatorSetString(INDICATOR_SHORTNAME, \"{name}({period})\");")
    lines.append("   IndicatorSetInteger(INDICATOR_DIGITS, _Digits);")
    if not in_main and levels:
        lines.append(f"   IndicatorSetDouble(INDICATOR_LEVELVALUE, 0, {level_high});")
        lines.append(f"   IndicatorSetDouble(INDICATOR_LEVELVALUE, 1, {level_low});")
    lines.append("   return(INIT_SUCCEEDED);")
    lines.append("}")
    lines.append("")

    lines.append("//+------------------------------------------------------------------+")
    lines.append("//| Indicator calculation                                             |")
    lines.append("//+------------------------------------------------------------------+")
    lines.append("int OnCalculate(const int rates_total,")
    lines.append("                const int prev_calculated,")
    lines.append("                const datetime &time[],")
    lines.append("                const double   &open[],")
    lines.append("                const double   &high[],")
    lines.append("                const double   &low[],")
    lines.append("                const double   &close[],")
    lines.append("                const long     &tick_volume[],")
    lines.append("                const long     &volume[],")
    lines.append("                const int      &spread[])")
    lines.append("{")
    lines.append(f"   if(rates_total < InpPeriod) return 0;")
    lines.append("")
    lines.append("   int start = (prev_calculated == 0) ? InpPeriod - 1 : prev_calculated - 1;")
    lines.append("")

    if "Moving Average" in ind_type:
        lines.append("   for(int i = start; i < rates_total; i++)")
        lines.append("   {")
        lines.append("      double sum = 0;")
        lines.append("      if(InpMAMethod == MODE_SMA)")
        lines.append("      {")
        lines.append("         for(int j = 0; j < InpPeriod; j++) sum += close[i - j];")
        lines.append("         MainBuffer[i] = sum / InpPeriod;")
        lines.append("      }")
        lines.append("      else if(InpMAMethod == MODE_EMA)")
        lines.append("      {")
        lines.append("         double k = 2.0 / (InpPeriod + 1);")
        lines.append("         if(i == InpPeriod - 1) { for(int j=0;j<InpPeriod;j++) sum+=close[j]; MainBuffer[i]=sum/InpPeriod; }")
        lines.append("         else MainBuffer[i] = close[i] * k + MainBuffer[i-1] * (1 - k);")
        lines.append("      }")
        lines.append("      else")
        lines.append("      {")
        lines.append("         for(int j = 0; j < InpPeriod; j++) sum += close[i - j];")
        lines.append("         MainBuffer[i] = sum / InpPeriod;")
        lines.append("      }")
        lines.append("   }")
    elif "RSI" in ind_type or "Oscillatore" in ind_type:
        lines.append("   for(int i = start; i < rates_total; i++)")
        lines.append("   {")
        lines.append("      double gains = 0, losses = 0;")
        lines.append("      for(int j = i - InpPeriod + 1; j <= i; j++)")
        lines.append("      {")
        lines.append("         double diff = close[j] - close[j-1];")
        lines.append("         if(diff > 0) gains  += diff;")
        lines.append("         else         losses -= diff;")
        lines.append("      }")
        lines.append("      double rs = (losses == 0) ? 100 : gains / losses;")
        lines.append("      MainBuffer[i] = 100 - (100 / (1 + rs));")
        lines.append("   }")
    elif "MACD" in ind_type:
        lines.append("   //--- Calcola EMA veloce e lenta")
        lines.append("   double ema_fast[], ema_slow[];")
        lines.append("   ArrayResize(ema_fast, rates_total);")
        lines.append("   ArrayResize(ema_slow, rates_total);")
        lines.append("   double kf = 2.0 / (InpFast + 1);")
        lines.append("   double ks = 2.0 / (InpSlow + 1);")
        lines.append("   ema_fast[0] = close[0];")
        lines.append("   ema_slow[0] = close[0];")
        lines.append("   for(int i = 1; i < rates_total; i++)")
        lines.append("   {")
        lines.append("      ema_fast[i] = close[i] * kf + ema_fast[i-1] * (1 - kf);")
        lines.append("      ema_slow[i] = close[i] * ks + ema_slow[i-1] * (1 - ks);")
        lines.append("      MainBuffer[i] = ema_fast[i] - ema_slow[i];")
        lines.append("   }")
        lines.append("   //--- Calcola Signal line (EMA del MACD)")
        lines.append("   double ks2 = 2.0 / (InpSignal + 1);")
        lines.append("   SignalBuffer[0] = MainBuffer[0];")
        lines.append("   for(int i = 1; i < rates_total; i++)")
        lines.append("      SignalBuffer[i] = MainBuffer[i] * ks2 + SignalBuffer[i-1] * (1 - ks2);")
    elif "Bollinger" in ind_type:
        lines.append("   for(int i = start; i < rates_total; i++)")
        lines.append("   {")
        lines.append("      double sum = 0;")
        lines.append("      for(int j = 0; j < InpPeriod; j++) sum += close[i - j];")
        lines.append("      double ma = sum / InpPeriod;")
        lines.append("      double variance = 0;")
        lines.append("      for(int j = 0; j < InpPeriod; j++) variance += MathPow(close[i-j] - ma, 2);")
        lines.append("      double stdev = MathSqrt(variance / InpPeriod);")
        lines.append("      MainBuffer[i] = ma;")
        lines.append("   }")
    elif "ATR" in ind_type:
        lines.append("   for(int i = start; i < rates_total; i++)")
        lines.append("   {")
        lines.append("      double sum = 0;")
        lines.append("      for(int j = 0; j < InpPeriod; j++)")
        lines.append("      {")
        lines.append("         double tr = MathMax(high[i-j], close[i-j-1]) - MathMin(low[i-j], close[i-j-1]);")
        lines.append("         sum += tr;")
        lines.append("      }")
        lines.append("      MainBuffer[i] = sum / InpPeriod;")
        lines.append("   }")
    elif "CCI" in ind_type:
        lines.append("   for(int i = start; i < rates_total; i++)")
        lines.append("   {")
        lines.append("      double typical = (high[i] + low[i] + close[i]) / 3.0;")
        lines.append("      double sum = 0;")
        lines.append("      for(int j = 0; j < InpPeriod; j++) sum += (high[i-j]+low[i-j]+close[i-j])/3.0;")
        lines.append("      double ma = sum / InpPeriod;")
        lines.append("      double md = 0;")
        lines.append("      for(int j = 0; j < InpPeriod; j++) md += MathAbs((high[i-j]+low[i-j]+close[i-j])/3.0 - ma);")
        lines.append("      md /= InpPeriod;")
        lines.append("      MainBuffer[i] = (md != 0) ? (typical - ma) / (0.015 * md) : 0;")
        lines.append("   }")
    elif "Momentum" in ind_type:
        lines.append("   for(int i = start; i < rates_total; i++)")
        lines.append("      MainBuffer[i] = (close[i - InpPeriod] != 0) ? (close[i] / close[i - InpPeriod]) * 100 : 0;")
    elif "Williams" in ind_type:
        lines.append("   for(int i = start; i < rates_total; i++)")
        lines.append("   {")
        lines.append("      double highest = high[ArrayMaximum(high, i - InpPeriod + 1, InpPeriod)];")
        lines.append("      double lowest  = low[ArrayMinimum(low,   i - InpPeriod + 1, InpPeriod)];")
        lines.append("      MainBuffer[i] = (highest != lowest) ? ((highest - close[i]) / (highest - lowest)) * -100 : 0;")
        lines.append("   }")
    else:
        lines.append("   for(int i = start; i < rates_total; i++)")
        lines.append("      MainBuffer[i] = close[i];")

    if arrows:
        lines.append("")
        lines.append("   //--- Calcola frecce")
        lines.append("   for(int i = start; i < rates_total - 1; i++)")
        lines.append("   {")
        lines.append("      ArrowBuy[i]  = EMPTY_VALUE;")
        lines.append("      ArrowSell[i] = EMPTY_VALUE;")
        lines.append("      if(i < 2) continue;")
        lines.append("      if(MainBuffer[i] > MainBuffer[i-1] && MainBuffer[i-1] <= MainBuffer[i-2])")
        lines.append("         ArrowBuy[i]  = low[i] - 5 * _Point;")
        lines.append("      if(MainBuffer[i] < MainBuffer[i-1] && MainBuffer[i-1] >= MainBuffer[i-2])")
        lines.append("         ArrowSell[i] = high[i] + 5 * _Point;")
        lines.append("   }")

    if alert or email or push:
        lines.append("")
        lines.append("   //--- Gestione notifiche (ultima candela chiusa)")
        lines.append("   if(InpAlerts && rates_total > 2)")
        lines.append("   {")
        lines.append("      int last = rates_total - 2;")
        lines.append("      bool condition = MainBuffer[last] > MainBuffer[last-1];")
        lines.append("      if(condition && !alerted)")
        lines.append("      {")
        lines.append(f"         string msg = \"{name}: segnale su \" + _Symbol;")
        if alert:
            lines.append("         Alert(msg);")
        if email:
            lines.append("         SendMail(\"MT5 Alert\", msg);")
        if push:
            lines.append("         SendNotification(msg);")
        lines.append("         alerted = true;")
        lines.append("      }")
        lines.append("      else if(!condition) alerted = false;")
        lines.append("   }")

    lines.append("")
    lines.append("   return(rates_total);")
    lines.append("}")

    return "\n".join(lines)
