def generate_script(p):
    name = p["name"]
    author = p["author"]
    version = p["version"]
    sc_type = p["type"]
    lot = p["lot"]
    sl = p["sl"]
    tp = p["tp"]
    magic = p["magic"]
    slippage = p["slippage"]
    confirm = p["confirm"]
    show_alert = p["alert"]
    add_comment = p["comment"]

    lines = []
    lines.append(f"//+------------------------------------------------------------------+")
    lines.append(f"//|  {name}.mq5                                                      |")
    lines.append(f"//|  Copyright 2025, {author}                                        |")
    lines.append(f"//|  Generated by MT5 Code Generator                                 |")
    lines.append(f"//+------------------------------------------------------------------+")
    lines.append(f"#property copyright \"Copyright 2025, {author}\"")
    lines.append(f"#property version   \"{version}\"")
    lines.append(f"#property script_show_inputs")
    lines.append(f"#property strict")
    lines.append("")
    lines.append("#include <Trade\\Trade.mqh>")
    lines.append("#include <Trade\\PositionInfo.mqh>")
    lines.append("#include <Trade\\OrderInfo.mqh>")
    lines.append("")

    needs_lot = "Apri" in sc_type
    needs_magic = int(magic) > 0

    lines.append("//--- Input Parameters")
    if needs_lot:
        lines.append(f"input double   InpLotSize    = {lot};       // Lotto")
        lines.append(f"input int      InpStopLoss   = {sl};        // Stop Loss (pips)")
        lines.append(f"input int      InpTakeProfit = {tp};       // Take Profit (pips)")
        lines.append(f"input int      InpSlippage   = {slippage};         // Slippage")
    if needs_magic or int(magic) == 0:
        lines.append(f"input int      InpMagic      = {magic};         // Magic Number (0=tutti)")
    if "Modifica" in sc_type:
        lines.append(f"input int      InpNewSL      = {sl};        // Nuovo Stop Loss (pips)")
        lines.append(f"input int      InpNewTP      = {tp};       // Nuovo Take Profit (pips)")
    lines.append("")

    lines.append("CTrade         trade;")
    lines.append("CPositionInfo  posInfo;")
    lines.append("COrderInfo     ordInfo;")
    lines.append("")

    lines.append("//+------------------------------------------------------------------+")
    lines.append("//| Script program start function                                     |")
    lines.append("//+------------------------------------------------------------------+")
    lines.append("void OnStart()")
    lines.append("{")

    if add_comment:
        lines.append(f"   //--- Script: {sc_type}")
        lines.append(f"   //--- Simbolo: \" + _Symbol")
        lines.append(f"   //--- Orario:  \" + (string)TimeCurrent()")
        lines.append("")

    if confirm:
        lines.append(f"   //--- Richiedi conferma")
        lines.append(f"   if(MessageBox(\"{sc_type}\\n\\nContinuare?\", \"{name}\", MB_YESNO | MB_ICONQUESTION) != IDYES)")
        lines.append(f"      return;")
        lines.append("")

    if needs_lot:
        lines.append("   if(InpLotSize <= 0) { Alert(\"Lotto non valido\"); return; }")

    if "Chiudi tutte" in sc_type:
        lines.append("   int closed = 0;")
        lines.append("   for(int i = PositionsTotal() - 1; i >= 0; i--)")
        lines.append("   {")
        lines.append("      if(!posInfo.SelectByIndex(i)) continue;")
        lines.append("      if(InpMagic != 0 && posInfo.Magic() != InpMagic) continue;")
        lines.append("      if(trade.PositionClose(posInfo.Ticket())) closed++;")
        lines.append("   }")
        if show_alert:
            lines.append("   Alert(\"Chiuse \" + (string)closed + \" posizioni\");")

    elif "solo posizioni BUY" in sc_type:
        lines.append("   int closed = 0;")
        lines.append("   for(int i = PositionsTotal() - 1; i >= 0; i--)")
        lines.append("   {")
        lines.append("      if(!posInfo.SelectByIndex(i)) continue;")
        lines.append("      if(InpMagic != 0 && posInfo.Magic() != InpMagic) continue;")
        lines.append("      if(posInfo.PositionType() == POSITION_TYPE_BUY)")
        lines.append("         if(trade.PositionClose(posInfo.Ticket())) closed++;")
        lines.append("   }")
        if show_alert:
            lines.append("   Alert(\"Chiuse \" + (string)closed + \" posizioni BUY\");")

    elif "solo posizioni SELL" in sc_type:
        lines.append("   int closed = 0;")
        lines.append("   for(int i = PositionsTotal() - 1; i >= 0; i--)")
        lines.append("   {")
        lines.append("      if(!posInfo.SelectByIndex(i)) continue;")
        lines.append("      if(InpMagic != 0 && posInfo.Magic() != InpMagic) continue;")
        lines.append("      if(posInfo.PositionType() == POSITION_TYPE_SELL)")
        lines.append("         if(trade.PositionClose(posInfo.Ticket())) closed++;")
        lines.append("   }")
        if show_alert:
            lines.append("   Alert(\"Chiuse \" + (string)closed + \" posizioni SELL\");")

    elif "in perdita" in sc_type:
        lines.append("   int closed = 0;")
        lines.append("   for(int i = PositionsTotal() - 1; i >= 0; i--)")
        lines.append("   {")
        lines.append("      if(!posInfo.SelectByIndex(i)) continue;")
        lines.append("      if(InpMagic != 0 && posInfo.Magic() != InpMagic) continue;")
        lines.append("      if(posInfo.Profit() < 0)")
        lines.append("         if(trade.PositionClose(posInfo.Ticket())) closed++;")
        lines.append("   }")
        if show_alert:
            lines.append("   Alert(\"Chiuse \" + (string)closed + \" posizioni in perdita\");")

    elif "in profitto" in sc_type:
        lines.append("   int closed = 0;")
        lines.append("   for(int i = PositionsTotal() - 1; i >= 0; i--)")
        lines.append("   {")
        lines.append("      if(!posInfo.SelectByIndex(i)) continue;")
        lines.append("      if(InpMagic != 0 && posInfo.Magic() != InpMagic) continue;")
        lines.append("      if(posInfo.Profit() > 0)")
        lines.append("         if(trade.PositionClose(posInfo.Ticket())) closed++;")
        lines.append("   }")
        if show_alert:
            lines.append("   Alert(\"Chiuse \" + (string)closed + \" posizioni in profitto\");")

    elif "ordine BUY" in sc_type:
        lines.append("   trade.SetDeviationInPoints(InpSlippage);")
        lines.append("   double ask    = SymbolInfoDouble(_Symbol, SYMBOL_ASK);")
        lines.append("   double point  = SymbolInfoDouble(_Symbol, SYMBOL_POINT);")
        lines.append("   int    digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);")
        lines.append("   double pip    = (digits == 5 || digits == 3) ? point * 10 : point;")
        lines.append("   double slPrice = (InpStopLoss  > 0) ? ask - InpStopLoss  * pip : 0;")
        lines.append("   double tpPrice = (InpTakeProfit > 0) ? ask + InpTakeProfit * pip : 0;")
        lines.append("   bool res = trade.Buy(InpLotSize, _Symbol, ask, slPrice, tpPrice);")
        if show_alert:
            lines.append("   if(res) Alert(\"BUY aperto su \" + _Symbol);")
            lines.append("   else    Alert(\"Errore apertura BUY: \" + (string)trade.ResultRetcode());")

    elif "ordine SELL" in sc_type:
        lines.append("   trade.SetDeviationInPoints(InpSlippage);")
        lines.append("   double bid    = SymbolInfoDouble(_Symbol, SYMBOL_BID);")
        lines.append("   double point  = SymbolInfoDouble(_Symbol, SYMBOL_POINT);")
        lines.append("   int    digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);")
        lines.append("   double pip    = (digits == 5 || digits == 3) ? point * 10 : point;")
        lines.append("   double slPrice = (InpStopLoss  > 0) ? bid + InpStopLoss  * pip : 0;")
        lines.append("   double tpPrice = (InpTakeProfit > 0) ? bid - InpTakeProfit * pip : 0;")
        lines.append("   bool res = trade.Sell(InpLotSize, _Symbol, bid, slPrice, tpPrice);")
        if show_alert:
            lines.append("   if(res) Alert(\"SELL aperto su \" + _Symbol);")
            lines.append("   else    Alert(\"Errore apertura SELL: \" + (string)trade.ResultRetcode());")

    elif "Cancella" in sc_type:
        lines.append("   int cancelled = 0;")
        lines.append("   for(int i = OrdersTotal() - 1; i >= 0; i--)")
        lines.append("   {")
        lines.append("      if(!ordInfo.SelectByIndex(i)) continue;")
        lines.append("      if(InpMagic != 0 && ordInfo.Magic() != InpMagic) continue;")
        lines.append("      if(trade.OrderDelete(ordInfo.Ticket())) cancelled++;")
        lines.append("   }")
        if show_alert:
            lines.append("   Alert(\"Cancellati \" + (string)cancelled + \" ordini pendenti\");")

    elif "Modifica SL/TP" in sc_type:
        lines.append("   double point  = SymbolInfoDouble(_Symbol, SYMBOL_POINT);")
        lines.append("   int    digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);")
        lines.append("   double pip    = (digits == 5 || digits == 3) ? point * 10 : point;")
        lines.append("   int modified = 0;")
        lines.append("   for(int i = PositionsTotal() - 1; i >= 0; i--)")
        lines.append("   {")
        lines.append("      if(!posInfo.SelectByIndex(i)) continue;")
        lines.append("      if(InpMagic != 0 && posInfo.Magic() != InpMagic) continue;")
        lines.append("      double openPrice = posInfo.PriceOpen();")
        lines.append("      double newSL, newTP;")
        lines.append("      if(posInfo.PositionType() == POSITION_TYPE_BUY)")
        lines.append("      {")
        lines.append("         newSL = (InpNewSL  > 0) ? openPrice - InpNewSL  * pip : 0;")
        lines.append("         newTP = (InpNewTP > 0) ? openPrice + InpNewTP * pip : 0;")
        lines.append("      }")
        lines.append("      else")
        lines.append("      {")
        lines.append("         newSL = (InpNewSL  > 0) ? openPrice + InpNewSL  * pip : 0;")
        lines.append("         newTP = (InpNewTP > 0) ? openPrice - InpNewTP * pip : 0;")
        lines.append("      }")
        lines.append("      if(trade.PositionModify(posInfo.Ticket(), newSL, newTP)) modified++;")
        lines.append("   }")
        if show_alert:
            lines.append("   Alert(\"Modificate \" + (string)modified + \" posizioni\");")

    elif "statistiche" in sc_type:
        lines.append("   //--- Analisi trade del giorno corrente")
        lines.append("   datetime today_start = StringToTime(TimeToString(TimeCurrent(), TIME_DATE));")
        lines.append("   double total_profit = 0;")
        lines.append("   int    total_trades = 0, wins = 0, losses = 0;")
        lines.append("   HistorySelect(today_start, TimeCurrent());")
        lines.append("   for(int i = 0; i < HistoryDealsTotal(); i++)")
        lines.append("   {")
        lines.append("      ulong ticket = HistoryDealGetTicket(i);")
        lines.append("      double profit = HistoryDealGetDouble(ticket, DEAL_PROFIT);")
        lines.append("      if(HistoryDealGetInteger(ticket, DEAL_ENTRY) == DEAL_ENTRY_OUT)")
        lines.append("      {")
        lines.append("         total_profit += profit;")
        lines.append("         total_trades++;")
        lines.append("         if(profit >= 0) wins++; else losses++;")
        lines.append("      }")
        lines.append("   }")
        lines.append("   double winrate = (total_trades > 0) ? (double)wins / total_trades * 100 : 0;")
        if show_alert:
            lines.append("   string stats = StringFormat(\"=== STATISTICHE OGGI ===\\n\"")
            lines.append("                              \"Trades: %d\\nWin: %d  Loss: %d\\n\"")
            lines.append("                              \"Win Rate: %.1f%%\\nProfitto: %.2f\",")
            lines.append("                              total_trades, wins, losses, winrate, total_profit);")
            lines.append("   Alert(stats);")

    elif "CSV" in sc_type:
        lines.append("   //--- Esporta history in CSV")
        lines.append("   string filename = _Symbol + \"_history_\" + TimeToString(TimeCurrent(), TIME_DATE) + \".csv\";")
        lines.append("   int fileHandle = FileOpen(filename, FILE_WRITE | FILE_CSV | FILE_ANSI, ',');")
        lines.append("   if(fileHandle == INVALID_HANDLE) { Alert(\"Impossibile creare file\"); return; }")
        lines.append("   FileWrite(fileHandle, \"Ticket\",\"Symbol\",\"Type\",\"Volume\",\"Open\",\"Close\",\"SL\",\"TP\",\"Profit\",\"Comment\");")
        lines.append("   HistorySelect(0, TimeCurrent());")
        lines.append("   for(int i = 0; i < HistoryDealsTotal(); i++)")
        lines.append("   {")
        lines.append("      ulong ticket = HistoryDealGetTicket(i);")
        lines.append("      if(HistoryDealGetInteger(ticket, DEAL_ENTRY) != DEAL_ENTRY_OUT) continue;")
        lines.append("      FileWrite(fileHandle,")
        lines.append("         (string)ticket,")
        lines.append("         HistoryDealGetString(ticket, DEAL_SYMBOL),")
        lines.append("         (HistoryDealGetInteger(ticket, DEAL_TYPE)==DEAL_TYPE_BUY ? \"BUY\" : \"SELL\"),")
        lines.append("         HistoryDealGetDouble(ticket, DEAL_VOLUME),")
        lines.append("         HistoryDealGetDouble(ticket, DEAL_PRICE),")
        lines.append("         HistoryDealGetDouble(ticket, DEAL_PRICE),")
        lines.append("         HistoryDealGetDouble(ticket, DEAL_SL),")
        lines.append("         HistoryDealGetDouble(ticket, DEAL_TP),")
        lines.append("         HistoryDealGetDouble(ticket, DEAL_PROFIT),")
        lines.append("         HistoryDealGetString(ticket, DEAL_COMMENT));")
        lines.append("   }")
        lines.append("   FileClose(fileHandle);")
        if show_alert:
            lines.append("   Alert(\"File esportato: \" + filename);")

    elif "Break Even" in sc_type:
        lines.append("   double point  = SymbolInfoDouble(_Symbol, SYMBOL_POINT);")
        lines.append("   int    digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);")
        lines.append("   double pip    = (digits == 5 || digits == 3) ? point * 10 : point;")
        lines.append("   int    be_count = 0;")
        lines.append("   for(int i = PositionsTotal() - 1; i >= 0; i--)")
        lines.append("   {")
        lines.append("      if(!posInfo.SelectByIndex(i)) continue;")
        lines.append("      if(InpMagic != 0 && posInfo.Magic() != InpMagic) continue;")
        lines.append("      double openPrice = posInfo.PriceOpen();")
        lines.append("      if(posInfo.PositionType() == POSITION_TYPE_BUY && posInfo.StopLoss() < openPrice)")
        lines.append("         if(trade.PositionModify(posInfo.Ticket(), openPrice, posInfo.TakeProfit())) be_count++;")
        lines.append("      if(posInfo.PositionType() == POSITION_TYPE_SELL && (posInfo.StopLoss() > openPrice || posInfo.StopLoss() == 0))")
        lines.append("         if(trade.PositionModify(posInfo.Ticket(), openPrice, posInfo.TakeProfit())) be_count++;")
        lines.append("   }")
        if show_alert:
            lines.append("   Alert(\"Break Even impostato su \" + (string)be_count + \" posizioni\");")

    lines.append("}")

    return "\n".join(lines)
